version: "2"

services:

  slack-api:
    image: databraiddb/slack-api:latest
    ports:
      - 8000:8000
    environment:
      - PORT=8000
    volumes:
      - ./.env.slack:/app/.env
      - ./google-credentials:/app/google-credentials

    depends_on:
      - postgres

  transit-api:
    image: databraiddb/transit-api:latest
    ports:
      - 8001:8000
    volumes:
      - ./.env.transit:/app/.env
    environment:
      - PORT=8000

  github-api:
    image: databraiddb/github-api:latest
    ports:
      - 8002:8000
    environment:
      - PORT=8000

  postgres:
    image: databraiddb/slack-test-postgres:latest
